### ISSUE TITLE
AttributeError: 'Search' object has no attribute 'args'

### ISSUE THREAD

**Issue by xuzhougeng** [allwefantasy/auto-coder#11]
运行日志如下

```
2024-05-18 18:41:34,471 INFO worker.py:1540 -- Connecting to existing Ray cluster at address: 10.10.87.98:6379...
2024-05-18 18:41:34,480 INFO worker.py:1715 -- Connected to Ray cluster. View the dashboard at 127.0.0.1:8265 
2024-05-18 18:41:34.520 | INFO     | autocoder.utils.llm_client_interceptors:token_counter_interceptor:16 - Input tokens count: 0, Generated tokens count: 0
2024-05-18 18:41:36.150 | INFO     | autocoder.utils.llm_client_interceptors:token_counter_interceptor:16 - Input tokens count: 841, Generated tokens count: 16
search SearchEngine.BING for 在 /tmp 目录下，创建一个符合 pip 标准的 python项目 t-py,注意不需要创建conda/venv环境
...
reraking the search result by snippets...
2024-05-18 18:41:38.471 | INFO     | autocoder.utils.llm_client_interceptors:token_counter_interceptor:16 - Input tokens count: 1923, Generated tokens count: 21
2024-05-18 18:41:39.750 | INFO     | autocoder.utils.llm_client_interceptors:token_counter_interceptor:16 - Input tokens count: 822, Generated tokens count: 27
fetch https://docs.python.org/zh-cn/3/tutorial/venv.html?highlight=pip and answer the quesion (在 /tmp 目录下，创建一个符合 pip 标准的 python项目 t-py,注意不需要创建conda/venv环境
) based on the full content...
Traceback (most recent call last):
  File "/home/xzg/miniforge3/envs/autocoder/bin/auto-coder", line 8, in <module>
    sys.exit(main())
  File "/home/xzg/miniforge3/envs/autocoder/lib/python3.10/site-packages/autocoder/auto_coder.py", line 228, in main
    dispacher.dispach()
  File "/home/xzg/miniforge3/envs/autocoder/lib/python3.10/site-packages/autocoder/dispacher/__init__.py", line 25, in dispach
    if action.run():
  File "/home/xzg/miniforge3/envs/autocoder/lib/python3.10/site-packages/autocoder/dispacher/actions/copilot.py", line 288, in run
    pp.run()
  File "/home/xzg/miniforge3/envs/autocoder/lib/python3.10/site-packages/autocoder/suffixproject/__init__.py", line 115, in run
    for code in self.get_search_source_codes():
  File "/home/xzg/miniforge3/envs/autocoder/lib/python3.10/site-packages/autocoder/suffixproject/__init__.py", line 78, in get_search_source_codes
    search_context = searcher.answer_with_the_most_related_context(self.args.query)  
  File "/home/xzg/miniforge3/envs/autocoder/lib/python3.10/site-packages/autocoder/common/search.py", line 384, in answer_with_the_most_related_context
    doc = HttpDoc(args = self.args,llm = self.llm,urls=[context.url])
AttributeError: 'Search' object has no attribute 'args'
```

auto-coder 的版本是 0.1.57
```
$ pip list |grep auto
auto-coder                              0.1.57
```

**Comment by allwefantasy** [comment]
We have fix this bug in 0.1.62. Try to use 

```bash
pip install -U auto-coder
```
and then test it again.
