### ISSUE TITLE
byzerllm query时报错：Failed to unpickle serialized exception

### ISSUE THREAD

**Issue by feiying00544** [allwefantasy/auto-coder#26]
运行“byzerllm query --model ollama_qwen2_chat --query "who are you"”时会报错：
ERROR serialization.py:425 -- Failed to unpickle serialized exception
Traceback (most recent call last):
  File "C:\Users\xxx\Miniconda3\envs\auto-coder\Lib\site-packages\ray\exceptions.py", line 50, in from_ray_exception
    return pickle.loads(ray_exception.serialized_exception)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: APIStatusError.__init__() missing 2 required keyword-only arguments: 'response' and 'body'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\xxx\Miniconda3\envs\auto-coder\Lib\site-packages\ray\_private\serialization.py", line 423, in deserialize_objects
    obj = self._deserialize_object(data, metadata, object_ref)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xxx\Miniconda3\envs\auto-coder\Lib\site-packages\ray\_private\serialization.py", line 305, in _deserialize_object
    return RayError.from_bytes(obj)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xxx\Miniconda3\envs\auto-coder\Lib\site-packages\ray\exceptions.py", line 44, in from_bytes
    return RayError.from_ray_exception(ray_exception)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xxx\Miniconda3\envs\auto-coder\Lib\site-packages\ray\exceptions.py", line 53, in from_ray_exception
    raise RuntimeError(msg) from e
RuntimeError: Failed to unpickle serialized exception
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\xxx\Miniconda3\envs\auto-coder\Scripts\byzerllm.exe\__main__.py", line 7, in <module>
  File "C:\Users\xxx\Miniconda3\envs\auto-coder\Lib\site-packages\byzerllm\byzerllm_command.py", line 125, in main
    resp = llm_client.chat_oai(
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xxx\Miniconda3\envs\auto-coder\Lib\site-packages\byzerllm\utils\client\byzerllm_client.py", line 1207, in chat_oai
    res = self._query(model, v)
          ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xxx\Miniconda3\envs\auto-coder\Lib\site-packages\byzerllm\utils\client\byzerllm_client.py", line 1873, in _query
    raise inst
  File "C:\Users\xxx\Miniconda3\envs\auto-coder\Lib\site-packages\byzerllm\utils\client\byzerllm_client.py", line 1863, in _query
    res = ray.get(worker.async_apply.remote(new_input_value))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xxx\Miniconda3\envs\auto-coder\Lib\site-packages\ray\_private\auto_init_hook.py", line 21, in auto_init_wrapper
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xxx\Miniconda3\envs\auto-coder\Lib\site-packages\ray\_private\client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xxx\Miniconda3\envs\auto-coder\Lib\site-packages\ray\_private\worker.py", line 2656, in get
    values, debugger_breakpoint = worker.get_objects(object_refs, timeout=timeout)
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xxx\Miniconda3\envs\auto-coder\Lib\site-packages\ray\_private\worker.py", line 873, in get_objects
    raise value
ray.exceptions.RaySystemError: System error: Failed to unpickle serialized exception
traceback: Traceback (most recent call last):
  File "C:\Users\xxx\Miniconda3\envs\auto-coder\Lib\site-packages\ray\exceptions.py", line 50, in from_ray_exception
    return pickle.loads(ray_exception.serialized_exception)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: APIStatusError.__init__() missing 2 required keyword-only arguments: 'response' and 'body'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\xxx\Miniconda3\envs\auto-coder\Lib\site-packages\ray\_private\serialization.py", line 423, in deserialize_objects
    obj = self._deserialize_object(data, metadata, object_ref)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xxx\Miniconda3\envs\auto-coder\Lib\site-packages\ray\_private\serialization.py", line 305, in _deserialize_object
    return RayError.from_bytes(obj)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xxx\Miniconda3\envs\auto-coder\Lib\site-packages\ray\exceptions.py", line 44, in from_bytes
    return RayError.from_ray_exception(ray_exception)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xxx\Miniconda3\envs\auto-coder\Lib\site-packages\ray\exceptions.py", line 53, in from_ray_exception
    raise RuntimeError(msg) from e
RuntimeError: Failed to unpickle serialized exception

**Comment by fansir** [comment]
一样的问题，解决了吗？

**Comment by hanfangyuan4396** [comment]
我是 在coding时 model_input_max_length配置的太小了出现了这个问题

**Comment by yx135790** [comment]
same here , when i deploy ` deepseek-ai/deepseek-v2-chat` model ,but the `deepseek-chat` model works file

**Comment by yx135790** [comment]
> same here , when i deploy ` deepseek-ai/deepseek-v2-chat` model ,but the `deepseek-chat` model works file

I was using a wrong API key ,My problem solved after i switch to a correct api Key.
This issue might due to exception serialization. but I don't know for details

**Comment by Sean10** [comment]
根据﻿​﻿​‌​‬‬​﻿‬​‌​​​​​﻿​﻿​‌‍​‌‍‌‌‍​​​​⁠​‬⁠﻿​﻿​​﻿‌‬﻿‬使用auto_coder遇到的问题及解决方案汇总 - 飞书云文档 这里的指导

可以去ray的dashboard查看, localhost:8265 看actor下面的log

我的环境这个报错最后是知识库token超了
openai.BadRequestError: Error code: 400 - {'code': 20015, 'message': 'length of prompt_tokens (434052) must be less than max_seq_len (32768).', 'data': None}

处理掉之后, 可以返回内容了. 只不过好像多个文件加起来不能超大模型的上下文, deepseek 128K超了还是会报错.

**Comment by zqc1661586344** [comment]
解决了没
