### ISSUE TITLE
ray start --head报错

### ISSUE THREAD

**Issue by shaomq21** [allwefantasy/auto-coder#28]
ray start --head报错，提示there was an error connecting to Redis.

(auto-coder) C:\Windows\System32>ray start --head
Usage stats collection is disabled.

Local node IP: 127.0.0.1
Traceback (most recent call last):
  File "C:\Users\shaom\.conda\envs\auto-coder\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\shaom\.conda\envs\auto-coder\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\shaom\.conda\envs\auto-coder\Scripts\ray.exe\__main__.py", line 7, in <module>
  File "C:\Users\shaom\.conda\envs\auto-coder\lib\site-packages\ray\scripts\scripts.py", line 2615, in main
    return cli()
  File "C:\Users\shaom\.conda\envs\auto-coder\lib\site-packages\click\core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\shaom\.conda\envs\auto-coder\lib\site-packages\click\core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "C:\Users\shaom\.conda\envs\auto-coder\lib\site-packages\click\core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\shaom\.conda\envs\auto-coder\lib\site-packages\click\core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\shaom\.conda\envs\auto-coder\lib\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\shaom\.conda\envs\auto-coder\lib\site-packages\ray\autoscaler\_private\cli_logger.py", line 856, in wrapper
    return f(*args, **kwargs)
  File "C:\Users\shaom\.conda\envs\auto-coder\lib\site-packages\ray\scripts\scripts.py", line 794, in start
    node = ray._private.node.Node(
  File "C:\Users\shaom\.conda\envs\auto-coder\lib\site-packages\ray\_private\node.py", line 333, in __init__
    self.start_head_processes()
  File "C:\Users\shaom\.conda\envs\auto-coder\lib\site-packages\ray\_private\node.py", line 1352, in start_head_processes
    self._write_cluster_info_to_kv()
  File "C:\Users\shaom\.conda\envs\auto-coder\lib\site-packages\ray\_private\node.py", line 1307, in _write_cluster_info_to_kv
    assert curr_val == self._session_name.encode("utf-8"), (
AssertionError: Session name session_2024-07-23_11-18-13_747975_14728 does not match persisted value b'session_2024-07-23_10-56-15_899692_20884'. Perhaps there was an error connecting to Redis.

**Comment by tedczj** [comment]
# ray stop 并重新deploy模型
ray stop
rm -rf /tmp/ray/session_*
ray start --head

**Comment by zhangsancode** [comment]
windows 下有可能是编码设置为题，系统编码设置成utf-8后成功启动
