### ISSUE TITLE
执行auto-coder命令byzerllm报错

### ISSUE THREAD

**Issue by nsdagi** [allwefantasy/auto-coder#3]
环境：ubuntu20.04,python3.10
执行以下命令，byzerllm报错
`auto-coder --file autocoder-human_as_model.yml `

```yml
source_dir: /tmp/t-py
target_file: /home/winubuntu/projects/ByzerRawCopilot/output.txt 

model: qianwen_chat
model_max_length: 2000
model_max_input_length: 6000
anti_quota_limit: 5

search_engine: bing
search_engine_token: ENV {{BING_SEARCH_TOKEN}}

## execute the prompt generated by auto-coder
execute: true
## extract the code from the prompt generated by auto-coder 
## and overwrite the source code
auto_merge: true

project_type: py

human_as_model: true

query: >
  在 read_root 方法前新添加一个方法，
  对应的rest 路径为 /hello, 
  输出返回值为  "world"  
```
via https://github.com/allwefantasy/auto-coder/blob/master/docs/zh/003-%20AutoCoder%20%E4%BD%BF%E7%94%A8Web%E7%89%88%E5%A4%A7%E6%A8%A1%E5%9E%8B%EF%BC%8C%E6%80%A7%E6%84%9F%E7%9A%84Human%20As%20Model%20%E6%A8%A1%E5%BC%8F.md

报错
```
--------------------------------------------------
Traceback (most recent call last):
  File "/home/ubd/auto-coder/.conda_autocoder/bin/auto-coder", line 8, in <module>
    sys.exit(main())
  File "/home/ubd/auto-coder/.conda_autocoder/lib/python3.10/site-packages/autocoder/auto_coder.py", line 165, in main
    byzerllm.connect_cluster()        
  File "/home/ubd/auto-coder/.conda_autocoder/lib/python3.10/site-packages/byzerllm/utils/connect_ray.py", line 31, in connect_cluster
    "PATH":f'''{os.path.join(java_home,"bin")}:{path}'''}
  File "/home/ubd/auto-coder/.conda_autocoder/lib/python3.10/posixpath.py", line 76, in join
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not **NoneType**
```

**Comment by baijingui** [comment]
设置java_home环境变量试试

**Comment by linuaries** [comment]
先安装Java，再设置JAVA_HOME

sudo apt install default-jdk
which javac
readlink -f `which java`  #获得在Ubuntu中java的路径
export JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64/bin/java
cp ~/.bashrc ~/.bashrc.bak
echo "export JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64/bin/java" >> ~/.bashrc
tail -3 ~/.bashrc
