### ISSUE TITLE
auto-coder --file 时，遇到 RuntimeError: Failed to unpickle serialized exception，怎么办？

### ISSUE THREAD

**Issue by 45592858** [allwefantasy/auto-coder#31]
2024-08-19 16:59:19.187 | INFO     | autocoder.index.index:get_target_files_by_query:401 - Find the related files by query according to the files...
2024-08-19 16:59:20,779 ERROR serialization.py:425 -- Failed to unpickle serialized exception
Traceback (most recent call last):
  File "/root/miniconda3/envs/auto-coder/lib/python3.10/site-packages/ray/exceptions.py", line 50, in from_ray_exception
    return pickle.loads(ray_exception.serialized_exception)
TypeError: APIStatusError.__init__() missing 2 required keyword-only arguments: 'response' and 'body'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/miniconda3/envs/auto-coder/lib/python3.10/site-packages/ray/_private/serialization.py", line 423, in deserialize_objects
    obj = self._deserialize_object(data, metadata, object_ref)
  File "/root/miniconda3/envs/auto-coder/lib/python3.10/site-packages/ray/_private/serialization.py", line 305, in _deserialize_object
    return RayError.from_bytes(obj)
  File "/root/miniconda3/envs/auto-coder/lib/python3.10/site-packages/ray/exceptions.py", line 44, in from_bytes
    return RayError.from_ray_exception(ray_exception)
  File "/root/miniconda3/envs/auto-coder/lib/python3.10/site-packages/ray/exceptions.py", line 53, in from_ray_exception
    raise RuntimeError(msg) from e
RuntimeError: Failed to unpickle serialized exception
Traceback (most recent call last):
  File "/root/miniconda3/envs/auto-coder/bin/auto-coder", line 8, in <module>
    sys.exit(main())
  File "/root/miniconda3/envs/auto-coder/lib/python3.10/site-packages/autocoder/auto_coder.py", line 774, in main
  File "/root/miniconda3/envs/auto-coder/lib/python3.10/site-packages/ray/exceptions.py", line 50, in from_ray_exception
    return pickle.loads(ray_exception.serialized_exception)
TypeError: APIStatusError.__init__() missing 2 required keyword-only arguments: 'response' and 'body'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/miniconda3/envs/auto-coder/lib/python3.10/site-packages/ray/_private/serialization.py", line 423, in deserialize_objects
    obj = self._deserialize_object(data, metadata, object_ref)
  File "/root/miniconda3/envs/auto-coder/lib/python3.10/site-packages/ray/_private/serialization.py", line 305, in _deserialize_object
    return RayError.from_bytes(obj)
  File "/root/miniconda3/envs/auto-coder/lib/python3.10/site-packages/ray/exceptions.py", line 44, in from_bytes
    return RayError.from_ray_exception(ray_exception)
  File "/root/miniconda3/envs/auto-coder/lib/python3.10/site-packages/ray/exceptions.py", line 53, in from_ray_exception
    raise RuntimeError(msg) from e
RuntimeError: Failed to unpickle serialized exception

**Comment by Ubivision** [comment]
我也遇到了同样的问题，在使用暴力RAG提问时报错，不知道是ray版本的问题还是啥问题

**Comment by 45592858** [comment]
求作者回复，让大家都能用起来 。。。@allwefantasy

**Comment by levicode** [comment]
同样的报错+1

**Comment by Sean10** [comment]
根据[﻿​﻿​‌​‬‬​﻿‬​‌​​​​​﻿​﻿​‌‍​‌‍‌‌‍​​​​⁠​‬⁠﻿​﻿​​﻿‌‬﻿‬使用auto\_coder遇到的问题及解决方案汇总 \- 飞书云文档](https://uelng8wukz.feishu.cn/wiki/F7OBwP7LYiS3lakQrwCchEUNndK?fromScene=spaceOverview) 这里的指导

可以去ray的dashboard查看, localhost:8265 看actor下面的log

我的环境这个报错最后是知识库token超了
openai.BadRequestError: Error code: 400 - {'code': 20015, 'message': 'length of prompt_tokens (434052) must be less than max_seq_len (32768).', 'data': None}

**Comment by zqc1661586344** [comment]
解决了没

**Comment by zjh7890** [comment]
排查指南：https://uelng8wukz.feishu.cn/wiki/SB4qwx7qyikDwqkPbjacn21Ynhf
