### ISSUE TITLE
sonnet3.5 模型部署成功，但无法chat

### ISSUE THREAD

**Issue by hanzch** [allwefantasy/auto-coder#44]
deploy sonnet3.5 --token  xxx 部署成功

```bash

✓ Ray is already running
2024-09-29 21:11:13,833 INFO worker.py:1601 -- Connecting to existing Ray cluster at address: 172.18.5.20:6379...
2024-09-29 21:11:13,838 INFO worker.py:1777 -- Connected to Ray cluster. View the dashboard at http://127.0.0.1:8265
Failed to look up actor with name 'sonnet3.5'. This could because 1. You are trying to look up a named actor you didn't create. 2. The named actor died. 3. You did not use a namespace matching the namespace of the actor.
Model sonnet3.5 deployed successfully



$ easy-byzerllm chat sonnet3.5 你好
Command Line Arguments:
--------------------------------------------------
command             : query
ray_address         : auto
model               : sonnet3.5
query               : 你好
template            : auto
file                : None
output_file         :
--------------------------------------------------
✓ Ray is already running
2024-09-29 21:11:25,060 INFO worker.py:1601 -- Connecting to existing Ray cluster at address: 172.18.5.20:6379...
2024-09-29 21:11:25,065 INFO worker.py:1777 -- Connected to Ray cluster. View the dashboard at http://127.0.0.1:8265
2024-09-29 21:11:27,519 ERROR serialization.py:425 -- Failed to unpickle serialized exception
Traceback (most recent call last):
  File "/root/miniconda3/envs/auto-coder/lib/python3.12/site-packages/ray/exceptions.py", line 50, in from_ray_exception
    return pickle.loads(ray_exception.serialized_exception)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: APIStatusError.__init__() missing 2 required keyword-only arguments: 'response' and 'body'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/miniconda3/envs/auto-coder/lib/python3.12/site-packages/ray/_private/serialization.py", line 423, in deserialize_objects
    obj = self._deserialize_object(data, metadata, object_ref)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/auto-coder/lib/python3.12/site-packages/ray/_private/serialization.py", line 305, in _deserialize_object
    return RayError.from_bytes(obj)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/auto-coder/lib/python3.12/site-packages/ray/exceptions.py", line 44, in from_bytes
    return RayError.from_ray_exception(ray_exception)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/auto-coder/lib/python3.12/site-packages/ray/exceptions.py", line 53, in from_ray_exception
    raise RuntimeError(msg) from e
RuntimeError: Failed to unpickle serialized exception
Traceback (most recent call last):
  File "/root/miniconda3/envs/auto-coder/bin/easy-byzerllm", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/root/miniconda3/envs/auto-coder/lib/python3.12/site-packages/byzerllm/easy_byzerllm_command.py", line 138, in main
    byzerllm_main(
  File "/root/miniconda3/envs/auto-coder/lib/python3.12/site-packages/byzerllm/byzerllm_command.py", line 143, in main
    resp = llm_client.chat_oai(
           ^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/auto-coder/lib/python3.12/site-packages/byzerllm/utils/client/byzerllm_client.py", line 1213, in chat_oai
    res = self._query(model, v)
          ^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/auto-coder/lib/python3.12/site-packages/byzerllm/utils/client/byzerllm_client.py", line 1887, in _query
    raise inst
  File "/root/miniconda3/envs/auto-coder/lib/python3.12/site-packages/byzerllm/utils/client/byzerllm_client.py", line 1877, in _query
    res = ray.get(worker.async_apply.remote(new_input_value))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/auto-coder/lib/python3.12/site-packages/ray/_private/auto_init_hook.py", line 21, in auto_init_wrapper
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/auto-coder/lib/python3.12/site-packages/ray/_private/client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/auto-coder/lib/python3.12/site-packages/ray/_private/worker.py", line 2691, in get
    values, debugger_breakpoint = worker.get_objects(object_refs, timeout=timeout)
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/auto-coder/lib/python3.12/site-packages/ray/_private/worker.py", line 873, in get_objects
    raise value
ray.exceptions.RaySystemError: System error: Failed to unpickle serialized exception
traceback: Traceback (most recent call last):
  File "/root/miniconda3/envs/auto-coder/lib/python3.12/site-packages/ray/exceptions.py", line 50, in from_ray_exception
    return pickle.loads(ray_exception.serialized_exception)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: APIStatusError.__init__() missing 2 required keyword-only arguments: 'response' and 'body'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/miniconda3/envs/auto-coder/lib/python3.12/site-packages/ray/_private/serialization.py", line 423, in deserialize_objects
    obj = self._deserialize_object(data, metadata, object_ref)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/auto-coder/lib/python3.12/site-packages/ray/_private/serialization.py", line 305, in _deserialize_object
    return RayError.from_bytes(obj)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/auto-coder/lib/python3.12/site-packages/ray/exceptions.py", line 44, in from_bytes
    return RayError.from_ray_exception(ray_exception)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/auto-coder/lib/python3.12/site-packages/ray/exceptions.py", line 53, in from_ray_exception
    raise RuntimeError(msg) from e
RuntimeError: Failed to unpickle serialized exception

**Comment by Sean10** [comment]
根据[﻿​﻿​‌​‬‬​﻿‬​‌​​​​​﻿​﻿​‌‍​‌‍‌‌‍​​​​⁠​‬⁠﻿​﻿​​﻿‌‬﻿‬使用auto_coder遇到的问题及解决方案汇总 - 飞书云文档](https://uelng8wukz.feishu.cn/wiki/F7OBwP7LYiS3lakQrwCchEUNndK?fromScene=spaceOverview) 这里的指导

可以去ray的dashboard查看, localhost:8265 看actor下面的log

我的环境这个报错最后是知识库token超了
openai.BadRequestError: Error code: 400 - {'code': 20015, 'message': 'length of prompt_tokens (434052) must be less than max_seq_len (32768).', 'data': None}

**Comment by hanzch** [comment]
> 根据[﻿​﻿​‌​‬‬​﻿‬​‌​​​​​﻿​﻿​‌‍​‌‍‌‌‍​​​​⁠​‬⁠﻿​﻿​​﻿‌‬﻿‬使用auto_coder遇到的问题及解决方案汇总 - 飞书云文档](https://uelng8wukz.feishu.cn/wiki/F7OBwP7LYiS3lakQrwCchEUNndK?fromScene=spaceOverview) 这里的指导
> 
> 可以去ray的dashboard查看, localhost:8265 看actor下面的log
> 
> 我的环境这个报错最后是知识库token超了 openai.BadRequestError: Error code: 400 - {'code': 20015, 'message': 'length of prompt_tokens (434052) must be less than max_seq_len (32768).', 'data': None}

感谢大佬，根据文档问题排查出来了。

**Comment by littlewwwhite** [comment]
> > 根据[﻿​﻿​‌​‬‬​﻿‬​‌​​​​​﻿​﻿​‌‍​‌‍‌‌‍​​​​⁠​‬⁠﻿​﻿​​﻿‌‬﻿‬使用 auto_coder 遇到的问题及解决方案汇总 - 飞书云文档](https://uelng8wukz.feishu.cn/wiki/F7OBwP7LYiS3lakQrwCchEUNndK?fromScene=spaceOverview) 这里的指导
> > 可以去 ray 的 dashboard 查看，localhost:8265 看 actor 下面的 log
> > 我的环境这个报错最后是知识库 token 超了 openai.BadRequestError: Error code: 400 - {'code': 20015, 'message': 'length of prompt_tokens (434052) must be less than max_seq_len (32768).', 'data': None}
> 
> 感谢大佬，根据文档问题排查出来了。

你好，想问下你是怎么排查的，我的 log 里面没有找到报错。但是和你的报错一样

**Comment by littlewwwhite** [comment]
> > > 根据[﻿​﻿​‌​‬‬​﻿‬​‌​​​​​﻿​﻿​‌‍​‌‍‌‌‍​​​​⁠​‬⁠﻿​﻿​​﻿‌‬﻿‬使用 auto_coder 遇到的问题及解决方案汇总 - 飞书云文档](https://uelng8wukz.feishu.cn/wiki/F7OBwP7LYiS3lakQrwCchEUNndK?fromScene=spaceOverview) 这里的指导
> > > 可以去 ray 的 dashboard 查看，localhost:8265 看 actor 下面的 log
> > > 我的环境这个报错最后是知识库 token 超了 openai.BadRequestError: Error code: 400 - {'code': 20015, 'message': 'length of prompt_tokens (434052) must be less than max_seq_len (32768).', 'data': None}
> > 
> > 
> > 感谢大佬，根据文档问题排查出来了。
> 
> 你好，想问下你是怎么排查的，我的 log 里面没有找到报错。但是和你的报错一样

已搞定，感谢
