### ISSUE TITLE
在windows下运行新版autorag出现错误

### ISSUE THREAD

**Issue by caichicong** [allwefantasy/auto-coder#45]
在windows下运行autorag出现如下错误：
  
```
  | Traceback (most recent call last):
    |   File "C:\Python312\Lib\site-packages\autocoder\rag\long_context_rag.py", line 279, in stream_chat_oai
    |     return self._stream_chat_oai(
    |            ^^^^^^^^^^^^^^^^^^^^^^
    |   File "C:\Python312\Lib\site-packages\autocoder\rag\long_context_rag.py", line 416, in _stream_chat_oai
    |     final_relevant_docs = token_limiter.limit_tokens(
    |                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "C:\Python312\Lib\site-packages\autocoder\rag\token_limiter.py", line 120, in limit_tokens
    |     elif doc not in added_docs:
    |          ^^^^^^^^^^^^^^^^^^^^^
    | TypeError: unhashable type: 'SourceCode'

```

**Comment by caichicong** [comment]
安装最新版

```pip install -U auto-coder==0.1.173 ```

然后在管理员权限下启动命令行，没有出错了
