### ISSUE TITLE
Ubuntu下安装时候报错

### ISSUE THREAD

**Issue by sunweihunu** [allwefantasy/auto-coder#50]
auto-coder.chat

🚀 正在初始化系统...
✓ 项目初始化完成。
  正在检查Ray状态...
✓ Ray已经在运行。
  正在检查deepseek_chat模型可用性...
! deepseek_chat模型不可用。请选择一个提供商：
请输入您的API密钥： sk-by******************************************
  正在使用硅基流动部署deepseek_chat模型...
Command Line Arguments:
--------------------------------------------------
command             : deploy
ray_address         : auto
num_workers         : 1
worker_concurrency  : 1000
gpus_per_worker     : 0.0
cpus_per_worker     : 0.001
model_path          : 
pretrained_model_type: saas/openai
model               : deepseek_chat
infer_backend       : 
infer_params        : {'saas.base_url': 'https://api.siliconflow.cn/v1', 'saas.api_key': '******', 'saas.model': 'deepseek-ai/deepseek-v2-chat'}
file                : None
--------------------------------------------------
✓ Ray is already running
2024-11-27 23:07:14,509 INFO worker.py:1634 -- Connecting to existing Ray cluster at address: 192.168.1.103:6379...
2024-11-27 23:07:14,516 INFO worker.py:1810 -- Connected to Ray cluster. View the dashboard at 127.0.0.1:8265 
模型 deepseek_chat 已经部署过了  正在使用硅基流动部署deepseek_chat模型...
Command Line Arguments:
--------------------------------------------------
command             : deploy
ray_address         : auto
num_workers         : 1
worker_concurrency  : 1000
gpus_per_worker     : 0.0
cpus_per_worker     : 0.001
model_path          : 
pretrained_model_type: saas/openai
model               : deepseek_chat
infer_backend       : 
infer_params        : {'saas.base_url': 'https://api.siliconflow.cn/v1', 'saas.api_key': '******', 'saas.model': 'deepseek-ai/deepseek-v2-chat'}
file                : None
--------------------------------------------------
✓ Ray is already running
2024-11-27 23:07:14,509 INFO worker.py:1634 -- Connecting to existing Ray cluster at address: 192.168.1.103:6379...
2024-11-27 23:07:14,516 INFO worker.py:1810 -- Connected to Ray cluster. View the dashboard at 127.0.0.1:8265 
模型 deepseek_chat 已经部署过了
✓ 部署完成。
  正在验证部署...
✗ 验证失败。模型可能未正确部署。
! 请尝试使用以下命令手动启动模型：
  easy-byzerllm chat deepseek_chat 你好
✓ 初始化完成。

**Comment by sunweihunu** [comment]
easy-byzerllm chat deepseek_chat 你好


Command Line Arguments:
--------------------------------------------------
command             : query
ray_address         : auto
model               : deepseek_chat
query               : 你好
template            : auto
file                : None
output_file         : 
--------------------------------------------------
✓ Ray is already running
2024-11-27 23:13:52,988 INFO worker.py:1634 -- Connecting to existing Ray cluster at address: 192.168.1.103:6379...
2024-11-27 23:13:52,996 INFO worker.py:1810 -- Connected to Ray cluster. View the dashboard at 127.0.0.1:8265 
2024-11-27 23:13:53,665 ERROR serialization.py:462 -- Failed to unpickle serialized exception
Traceback (most recent call last):
  File "/home/dell/.local/lib/python3.10/site-packages/ray/exceptions.py", line 51, in from_ray_exception
    return pickle.loads(ray_exception.serialized_exception)
TypeError: APIStatusError.__init__() missing 2 required keyword-only arguments: 'response' and 'body'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/dell/.local/lib/python3.10/site-packages/ray/_private/serialization.py", line 460, in deserialize_objects
    obj = self._deserialize_object(data, metadata, object_ref)
  File "/home/dell/.local/lib/python3.10/site-packages/ray/_private/serialization.py", line 342, in _deserialize_object
    return RayError.from_bytes(obj)
  File "/home/dell/.local/lib/python3.10/site-packages/ray/exceptions.py", line 45, in from_bytes
    return RayError.from_ray_exception(ray_exception)
  File "/home/dell/.local/lib/python3.10/site-packages/ray/exceptions.py", line 54, in from_ray_exception
    raise RuntimeError(msg) from e
RuntimeError: Failed to unpickle serialized exception
Traceback (most recent call last):
  File "/home/dell/.local/bin/easy-byzerllm", line 8, in <module>
    sys.exit(main())
  File "/home/dell/.local/lib/python3.10/site-packages/byzerllm/easy_byzerllm_command.py", line 138, in main
    byzerllm_main(
  File "/home/dell/.local/lib/python3.10/site-packages/byzerllm/byzerllm_command.py", line 147, in main
    resp = llm_client.chat_oai(
  File "/home/dell/.local/lib/python3.10/site-packages/byzerllm/utils/client/byzerllm_client.py", line 1213, in chat_oai
    res = self._query(model, v)
  File "/home/dell/.local/lib/python3.10/site-packages/byzerllm/utils/client/byzerllm_client.py", line 1898, in _query
    raise inst
  File "/home/dell/.local/lib/python3.10/site-packages/byzerllm/utils/client/byzerllm_client.py", line 1888, in _query
    res = ray.get(worker.async_apply.remote(new_input_value))
  File "/home/dell/.local/lib/python3.10/site-packages/ray/_private/auto_init_hook.py", line 21, in auto_init_wrapper
    return fn(*args, **kwargs)
  File "/home/dell/.local/lib/python3.10/site-packages/ray/_private/client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
  File "/home/dell/.local/lib/python3.10/site-packages/ray/_private/worker.py", line 2753, in get
    values, debugger_breakpoint = worker.get_objects(object_refs, timeout=timeout)
  File "/home/dell/.local/lib/python3.10/site-packages/ray/_private/worker.py", line 906, in get_objects
    raise value
ray.exceptions.RaySystemError: System error: Failed to unpickle serialized exception
traceback: Traceback (most recent call last):
  File "/home/dell/.local/lib/python3.10/site-packages/ray/exceptions.py", line 51, in from_ray_exception
    return pickle.loads(ray_exception.serialized_exception)
TypeError: APIStatusError.__init__() missing 2 required keyword-only arguments: 'response' and 'body'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/dell/.local/lib/python3.10/site-packages/ray/_private/serialization.py", line 460, in deserialize_objects
    obj = self._deserialize_object(data, metadata, object_ref)
  File "/home/dell/.local/lib/python3.10/site-packages/ray/_private/serialization.py", line 342, in _deserialize_object
    return RayError.from_bytes(obj)
  File "/home/dell/.local/lib/python3.10/site-packages/ray/exceptions.py", line 45, in from_bytes
    return RayError.from_ray_exception(ray_exception)
  File "/home/dell/.local/lib/python3.10/site-packages/ray/exceptions.py", line 54, in from_ray_exception
    raise RuntimeError(msg) from e
RuntimeError: Failed to unpickle serialized exception

**Comment by allwefantasy** [comment]
参看这篇来排查：https://uelng8wukz.feishu.cn/wiki/CcAgwtL9TiuMEOkGoXbcKE3Gnfb?fromScene=spaceOverview

**Comment by xiangel** [comment]
也报了同样的错误，查看文档也没有解决，请问有其他方案么？

**Comment by allwefantasy** [comment]
> 也报了同样的错误，查看文档也没有解决，请问有其他方案么？

根据文档，把 ray 中的 err 日志贴出来哦

**Comment by xiangel** [comment]
测试了一下使用qwen就不报错，使用deepseek会报错，错误信息和前面的一致
