### ISSUE TITLE
macOS 下安装后执行报 AttributeError: 'NoneType' object has no attribute 'startswith' 错误

### ISSUE THREAD

**Issue by mintisan** [allwefantasy/auto-coder#6]
完全按照如下顺序安装：

```
conda create --name autocoder python==3.10.11
conda activate autocoder
pip install -U auto-coder
ray start --head
```

然后执行

```
(autocoder) ➜  ~ auto-coder -h        

/Users/mintisan/miniconda3/envs/autocoder/lib/python3.10/site-packages/pydantic/_internal/_fields.py:151: UserWarning: Field "model_max_length" has conflict with protected namespace "model_".

You may be able to resolve this warning by setting `model_config['protected_namespaces'] = ()`.
  warnings.warn(
/Users/mintisan/miniconda3/envs/autocoder/lib/python3.10/site-packages/pydantic/_internal/_fields.py:151: UserWarning: Field "model_max_input_length" has conflict with protected namespace "model_".

You may be able to resolve this warning by setting `model_config['protected_namespaces'] = ()`.
  warnings.warn(
/Users/mintisan/miniconda3/envs/autocoder/lib/python3.10/site-packages/langchain/__init__.py:29: UserWarning: Importing PromptTemplate from langchain root module is no longer supported. Please use langchain_core.prompts.PromptTemplate instead.
  warnings.warn(
Traceback (most recent call last):
  File "/Users/mintisan/miniconda3/envs/autocoder/bin/auto-coder", line 8, in <module>
    sys.exit(main())
  File "/Users/mintisan/miniconda3/envs/autocoder/lib/python3.10/site-packages/autocoder/auto_coder.py", line 103, in main
    args = parse_args()
  File "/Users/mintisan/miniconda3/envs/autocoder/lib/python3.10/site-packages/autocoder/auto_coder.py", line 69, in parse_args
    lang = "zh" if system_lang.startswith("zh") else "en"
AttributeError: 'NoneType' object has no attribute 'startswith'
(autocoder) ➜  ~ 

```

**Comment by Symbolk** [comment]
我这边是直接auto-coder.chat报[1]    90118 segmentation fault  auto-coder.chat，运行ray start --head也一样
