### ISSUE TITLE
Do auto-coder not support windows OS yet?

### ISSUE THREAD

**Issue by linuaries** [allwefantasy/auto-coder#9]
It is not easy to install deepspeed at Windows>_<  

Using cached https://pypi.tuna.tsinghua.edu.cn/packages/c4/d2/8ef74ea43580db602b845a499340ee21da98fb1e749d86ab9ee16bc32bd2/deepspeed-0.14.0.tar.gz (1.3 MB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [16 lines of output]
      [2024-04-04 23:39:28,213] [INFO] [real_accelerator.py:191:get_accelerator] Setting ds_accelerator to cuda (auto detect)
      test.c
      LINK : fatal error LNK1181: 无法打开输入文件“aio.lib”
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\Admin\AppData\Local\Temp\pip-install-27e1k48k\deepspeed_a0f3a262bf434364b2905a923883a817\setup.py", line 183, in <module>
          abort(f"Unable to pre-compile {op_name}")
        File "C:\Users\Admin\AppData\Local\Temp\pip-install-27e1k48k\deepspeed_a0f3a262bf434364b2905a923883a817\setup.py", line 52, in abort
          assert False, msg
      AssertionError: Unable to pre-compile async_io
      DS_BUILD_OPS=1
       [WARNING]  async_io requires the dev libaio .so object and headers but these were not found.
       [WARNING]  If libaio is already installed (perhaps from source), try setting the CFLAGS and LDFLAGS environment variables to where it can be found.
       [WARNING]  One can disable async_io with DS_BUILD_AIO=0
       [ERROR]  Unable to pre-compile async_io
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

**Comment by caichicong** [comment]
Please use it temporarily under Linux system.

**Comment by allwefantasy** [comment]
MacOS/Linux are  tested.

If you work on Windows, try to  pip install -U auto-coder to get the latest version, we have removed the deepspeed (optional) dependency

**Comment by PeterHou41** [comment]
@allwefantasy 在最新的requirements.txt中，**SwissArmyTransformer**依赖于deepspeed，加粗的包是否对客户端安装auto-coder起决定性作用吗？
